version: "2"
services:
  alfresco-postgresql:
    restart: always
    image: sameersbn/postgresql:latest
    volumes:
      - /srv/alfresco-postgresql:/var/lib/postgresql:Z
    environment:
      - DB_NAME=alfresco
      - DB_PASS=alfresco
      - DB_USER=alfresco
      - DB_EXTENSION=pg_trgm
    networks:
      - my-network
  alfresco:
    image: "gui81/alfresco"
    restart: always
    depends_on:
      - alfresco-postgresql
    volumes:
      - "/srv/alfresco/data:/alfresco/alf_data"
      - "/srv/alfresco/logs:/alfresco/tomcat/logs"
      - "/srv/alfresco/content:/content"
    environment:
      CONTENT_STORE: /content
      DB_HOST: alfresco-postgresql
      DB_KIND: postgresql
      DB_NAME: alfresco
      DB_PASSWORD: alfresco
      DB_USERNAME: alfresco
    networks:
      - my-network
  gitlab-redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - /srv/gitlab-redis:/var/lib/redis:Z
    networks:
      - my-network
  gitlab-postgresql:
    restart: always
    image: sameersbn/postgresql:latest
    volumes:
      - /srv/gitlab-postgresql:/var/lib/postgresql:Z
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm
    networks:
      - my-network
  gitlab:
    restart: always
    image: sameersbn/gitlab:latest
    ports:
      - "23:22"
    depends_on:
      - gitlab-redis
      - gitlab-postgresql
    volumes:
      - /srv/gitlab:/home/git/data:Z
    environment:
      - DEBUG=false

      - DB_ADAPTER=postgresql
      - DB_HOST=gitlab-postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379

      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_HOST=localhost
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_RELATIVE_URL_ROOT=/gitlab
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

      - GITLAB_ROOT_PASSWORD=
      - GITLAB_ROOT_EMAIL=

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - OAUTH_ENABLED=false
      - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
      - OAUTH_ALLOW_SSO=
      - OAUTH_BLOCK_AUTO_CREATED_USERS=true
      - OAUTH_AUTO_LINK_LDAP_USER=false
      - OAUTH_AUTO_LINK_SAML_USER=false
      - OAUTH_EXTERNAL_PROVIDERS=

      - OAUTH_CAS3_LABEL=cas3
      - OAUTH_CAS3_SERVER=
      - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
      - OAUTH_CAS3_LOGIN_URL=/cas/login
      - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
      - OAUTH_CAS3_LOGOUT_URL=/cas/logout

      - OAUTH_GOOGLE_API_KEY=
      - OAUTH_GOOGLE_APP_SECRET=
      - OAUTH_GOOGLE_RESTRICT_DOMAIN=

      - OAUTH_FACEBOOK_API_KEY=
      - OAUTH_FACEBOOK_APP_SECRET=

      - OAUTH_TWITTER_API_KEY=
      - OAUTH_TWITTER_APP_SECRET=

      - OAUTH_GITHUB_API_KEY=
      - OAUTH_GITHUB_APP_SECRET=
      - OAUTH_GITHUB_URL=
      - OAUTH_GITHUB_VERIFY_SSL=

      - OAUTH_GITLAB_API_KEY=
      - OAUTH_GITLAB_APP_SECRET=

      - OAUTH_BITBUCKET_API_KEY=
      - OAUTH_BITBUCKET_APP_SECRET=

      - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
      - OAUTH_SAML_IDP_CERT_FINGERPRINT=
      - OAUTH_SAML_IDP_SSO_TARGET_URL=
      - OAUTH_SAML_ISSUER=
      - OAUTH_SAML_LABEL="Our SAML Provider"
      - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      - OAUTH_SAML_GROUPS_ATTRIBUTE=
      - OAUTH_SAML_EXTERNAL_GROUPS=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

      - OAUTH_CROWD_SERVER_URL=
      - OAUTH_CROWD_APP_NAME=
      - OAUTH_CROWD_APP_PASSWORD=

      - OAUTH_AUTH0_CLIENT_ID=
      - OAUTH_AUTH0_CLIENT_SECRET=
      - OAUTH_AUTH0_DOMAIN=

      - OAUTH_AZURE_API_KEY=
      - OAUTH_AZURE_API_SECRET=
      - OAUTH_AZURE_TENANT_ID=
    networks:
      - my-network
  jenkins:
    restart: always
    user: root
    image: jenkins:latest
    volumes:
      - /srv/jenkins:/var/jenkins_home
      - /srv/jenkins/.ssh:/root/.ssh
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - my-network
  jenkins-slave:
    build: ./jenkins-slave
    image: cbn/jenkins-slave
    restart: always
    privileged: true
    volumes: 
      - /srv/jenkins-slave/docker:/var/lib/docker
      - /srv/jenkins-slave/data:/data
      - /srv/jenkins-slave/.ssh:/root/.ssh
    depends_on:
      - jenkins
    networks:
      - my-network
  redmine-postgresql:
    image: postgres
    restart: always
    volumes:
      - /srv/redmine-postgresql:/var/lib/postgresql
    networks:
      - my-network
    environment:
      - DB_PASS=password
      - DB_NAME=redmine
  redmine:
    build: ./redmine
    image: cbn/redmine
    restart: always
    environment:
      REDMINE_DB_POSTGRES: redmine-postgresql
      REDMINE_DB_PASSWORD: password
      RAILS_RELATIVE_URL_ROOT: /redmine
    volumes:
      - /srv/redmine:/usr/src/redmine/files
    networks: 
      - my-network
    depends_on:
      - redmine-postgresql
  adminer:
    restart: always
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - alfresco-postgresql
      - gitlab-postgresql
      - redmine-postgresql
  proxy:
    restart: always
    build: ./proxy
    image: cbn/proxy
    ports:
      - "80:80"
    volumes:
      - "/srv/nginx:/var/log/nginx"
    networks: 
      - my-network
    depends_on:
      - alfresco
      - gitlab
      - jenkins
      - redmine
networks:
  my-network: